#!/usr/bin/env bash
#MISE description="Run the container"
docker run -d \
  --name lucidvault \
  -e RAINDROP_ACCESS_TOKEN="${RAINDROP_ACCESS_TOKEN}" \
  -e OLLAMA_API_KEY="${OLLAMA_API_KEY}" \
  -e VAULT_PATH="${PWD}/test-vault" \
  -v "${PWD}/test-vault":/vault \
  lucidvault:latest
